[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "LBracket"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "RBracket"
mode = "Vi|~Search"
mods = "Control"

[window]
dynamic_title = true
opacity = 0.9

[env]
TERM = "xterm-256color"

[colors.primary]
background = "0x252b32"
foreground = "0xe0def4"

[font]
size = 13.0
